config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


#articles routes
#get 'articles', to: 'articles#index', as: 'articles'
#post 'articles', to: 'articles#create'
#get 'articles/new', to: 'articles#new', as: 'new_article'
#get 'articles/:id', to: 'articles#show', as: 'article'
#get 'articles/:id/edit', to: 'articles#edit', as: 'edit_article'
#patch 'articles/:id', to: 'articles#update'
#delete 'articles/:id', to: 'articles#destroy'

#authors routes
#get 'authors', to: 'authors#index', as: 'authors'
#post 'authors', to: 'authors#create'
#get 'authors/new', to: 'authors#new', as: 'new_author'
#get 'authors/:id', to: 'authors#show', as: 'author'
#get 'authors/:id/edit', to: 'authors#edit', as: 'edit_author'
#patch 'authors/:id', to: 'authors#update'
#delete 'authors/:id', to: 'authors#destroy'

resources :articles do
  resources :comments
end

resources :authors

#resorces :articles (resources sample)

root to: 'authors#index' #(to point root page)
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
    has_many :article_advertisements
    has_many :articles, through: :article_advertisements
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments #plural for one to many relationship
    validates :content, presence:true
    # validates :content, length: { minimum: 2, message: 'too short'}

    has_many :article_advertisements
    has_many :advertisements, through: :article_advertisements

    validate :check_length

    def check_length
        if !self.content.nil? && self.content.length > 50
            errors.add(:different_content, "Too long")
        end
    end
end

app/models/article_advertisement.rb
class ArticleAdvertisement < ApplicationRecord
  belongs_to :article
  belongs_to :advertisement
end

app/models/author.rb
class Author < ApplicationRecord
    #name validation
    validates :name, presence:true, uniqueness: true

    #address validation
    validates :address, presence:true

    #date validation
    validates :date, presence:true
    # validate :check_date

    # def check_date
    #     if !self.date.nil? && self.date < Date.today
    #         errors.add(:date, "This date should not be later than today!")
    #     end
    # end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/role.rb
class Role < ApplicationRecord
    #has_and_belongs_to_many :users

    #mono-intransitive
    has_many :user_roles
    has_many :users, through: :user_roles
end

app/models/user.rb
class User < ApplicationRecord
    #intransitive
    # has_and_belongs_to_many :roles


    #mono-intransitive
    has_many :user_roles
    has_many :roles, through: :user_roles
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :set_article, only: [:show,:edit,:update,:destroy]


    def index
        #render 'articles/show' (to render specific erb)
        @articles = Article.all
    end

    def show
        # @id = params[:id]
    end

    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to @article
        else
            render :new
        end
    end

    def update
        if @article.update(article_params)
            redirect_to @article
        else
            render :edit
        end
    end

    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :content)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

    before_action :set_author, only: [:show, :edit, :update, :destroy]

    def index   
        @authors = Author.all
    end

    def show
        # @id = params[:id]
    end

    def new
        @author = Author.new
    end

    def edit
    end

    def create
        @author = Author.new(author_params)

        if @author.save
            redirect_to @author
        else
            render :new
        end
    end

    def update
        if @author.update(author_params)
            redirect_to @author
        else
            render :edit
        end
    end

    def destroy
        @author.destroy
        redirect_to authors_path
    end

    private

    def set_author
        @author = Author.find(params[:id])
    end

    def author_params
        params.require(:author).permit(:name, :address, :date, :is_verified)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :get_article

    def index
        @comments = @article.comments
    end

    def new
        @comment = @article.comments.build
    end

    def create
        @comment = @article.comments.build(comment_params)

        if @comment.save
            redirect_to article_comments_path(@article.id)
        else
            render :new
        end
    end

    private

    def get_article
        @article = Article.find(params[:article_id])
    end

    def comment_params
        #params.require(:comment).permit(:body,:article_id)
        params.require(:comment).permit(:body) #can also be without article_id because its @article in def create
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<% if article.errors.any? %>
<% article.errors.each do |error| %>
<p> <%= error.full_message %> </p>

<% end %>
<% end %>


<%= form_with model: @article do |form| %>

<%= form.label :title %>
<%= form.text_field :title %>

<%= form.label :content %>
<%= form.text_field :content %>

<%= form.submit %>

<% end %>

app/views/articles/destroy.html.erb
<h1>Article destroy</h1>

app/views/articles/edit.html.erb
<h1>Articles Edit</h1>


<%= render 'form', article:@article %>

app/views/articles/index.html.erb
<h1> Hello index page! </h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Content</th>
        </tr>
    </thead>

    <tbody>
    <% @articles.each do |article| %>
        <tr>
            <td>
                <%= article.title %>
            </td>
            <td>
                <%= article.content %>
            </td>

            <td>
                <%= link_to 'Delete', article, method: :delete, data: {confirm: 'are you sure?'} %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/articles/index.html.haml
%h1 Hello index page!

%table
    %thead
        %tr
            %th Title
            %th Content
            %th Comment Count
            %th{colspan: "3"} Action

    %tbody
        - @articles.each do |article| 
            %tr
                %td= article.title
                %td= article.content
                %td= article.comments.count
                %td= link_to 'Comments', article_comments_path(article.id)
                %td= link_to 'Delete', article, method: :delete, data: {confirm: 'are you sure?'}

app/views/articles/new.html.erb
<h1>Articles new</h1>


<%= render 'form', article:@article %>

app/views/articles/show.html.erb
<h1> Hello from Show page! </h1>

<h1><%= @id %> </h1>

<%= link_to 'Go to articles page', articles_path %>

app/views/authors/_form.html.erb
<% if author.errors.any? %>
<% author.errors.each do |error| %>
<p> <%= error.full_message %> </p>

<% end %>
<% end %>


<%= form_with model: @author do |form| %>

<%= form.label :name %>
<%= form.text_field :name %>

<%= form.label :address %>
<%= form.text_field :address %>

<%= form.label :date %>
<%= form.date_select :date %>

<%= form.submit %>

<% end %>

app/views/authors/edit.html.erb
<h1>Authors#edit</h1>

<%= render 'form', author:@author %>

app/views/authors/index.html.erb
<h1>Authors#index page</h1>
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Address</th>
			<th>Date Verified</th>
			<th>Verified</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @authors.each do |author| %>
			<tr>
				<td>
					<%= author.name %>
				</td>
				<td>
					<%= author.address %>
				</td>
				<td>
					<%= author.date %>
				</td>
				<td>
					<% if author.is_verified %>
						<%= author.is_verified %>
					<% else %>
						<%= form_with model: author, method: :patch do |form| %>
							<%= form.hidden_field :is_verified, :value => true%>
							<%= form.button 'Verify', data: {confirm: "Verify author #{author.name}?"}%>
						<% end %>
					<% end %>
				</td>
				<td>
					<%= link_to 'Show', author_path(author), class: 'link' %>
				</td>
				<td>
					<%= link_to 'Delete', author, method: :delete, data: {confirm: "Remove author #{author.name}?"}, class: 'link'%>
				</td>
				<td>
					<%= link_to 'Edit', edit_author_path(author), class: 'link' %>
				</td>
			</tr>
		<% end%>
	</tbody>
</table>
<button class='btn'>
	<%= link_to 'Create New Author', new_author_path, class: 'link' %>
</button>

app/views/authors/new.html.erb
<h1>Authors#new</h1>


<%= render 'form', author:@author %>

app/views/authors/show.html.erb
<h1>Author#show page</h1>
<table>
	<tr>
		<td>
			Title:
		</td>
		<td>
			<%= @author.name%>
		</td>
	</tr>
	<tr>
		<td>
			Address:
		</td>
		<td>
			<%= @author.address%>
		</td>
	</tr>
	<tr>
		<td>
			Date Verified:
		</td>
		<td>
			<%= @author.date%>
		</td>
	</tr>
	<tr>
		<td>
			Verified:
		</td>
		<td >
			<%= @author.is_verified%>
		</td>
		<% if !@author.is_verified %>
			<td>
				<%= form_with model: @author, method: :patch do |form| %>
					<%= form.hidden_field :is_verified, :value => true%>
					<%= form.button 'Verify', data: {confirm: 'Verify author?'}%>
				<% end %>
			</td>
		<% end %>
	</tr>
	<tr>
	</tr>
</table>
<%= link_to 'Go to authors page', authors_path%>

app/views/comments/index.html.haml
%h2= @article.title

%h2 Comments 

%table
    %thead
        %tr
            %th Comment Body
            %th Action

    %tbody
        - @comments.each do |comment| 
            %tr
                %td= comment.body
               

app/views/comments/new.html.haml
= form_with scope: :comment, model: [@article,@comment] do |form|
    %p
        = form.label :body
        = form.text_field :body

    %p
        = form.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>